### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by bstamps** [fangly/AmpliCopyrighter#1]
Error after executing 

copyrighter -i otu_table.biom -o copyrighted_otu.biom

Reading input file 'otu_table.biom'
Attribute (weight_files) does not pass the type constraint because: Validation failed for 'ArrayRefOfReadableFileHandles' with value [ "/media/Storage/AmpliCopyrighter/data/201210/:" ] at /usr/lib/perl5/Moose/Meta/Attribute.pm line 1274.
    Moose::Meta::Attribute::verify_against_type_constraint('Moose::Meta::Attribute=HASH(0x3d254b0)', 'ARRAY(0x3f776f0)', 'instance', 'Bio::Community::IO::Driver::biom=HASH(0x4080298)') called at /usr/lib/perl5/Moose/Meta/Attribute.pm line 1261
    Moose::Meta::Attribute::_coerce_and_verify('Moose::Meta::Attribute=HASH(0x3d254b0)', 'ARRAY(0x3f776f0)', 'Bio::Community::IO::Driver::biom=HASH(0x4080298)') called at /usr/lib/perl5/Moose/Meta/Attribute.pm line 531
    Moose::Meta::Attribute::initialize_instance_slot('Moose::Meta::Attribute=HASH(0x3d254b0)', 'Moose::Meta::Instance=HASH(0x44dbe10)', 'Bio::Community::IO::Driver::biom=HASH(0x4080298)', 'HASH(0x210c990)') called at /usr/lib/perl5/Class/MOP/Class.pm line 525
    Class::MOP::Class::_construct_instance('Class::MOP::Class::Immutable::Moose::Meta::Class::__ANON__::S...', 'HASH(0x210c990)') called at /usr/lib/perl5/Class/MOP/Class.pm line 498
    Class::MOP::Class::new_object('Class::MOP::Class::Immutable::Moose::Meta::Class::**ANON**::S...', 'HASH(0x210c990)') called at /usr/lib/perl5/Moose/Meta/Class.pm line 274
    Moose::Meta::Class::new_object('Class::MOP::Class::Immutable::Moose::Meta::Class::**ANON**::S...', 'HASH(0x210c990)') called at /usr/local/share/perl/5.14.2/Bio/Community/IO.pm line 244
    Bio::Community::IO::new('Bio::Community::IO', '-file', 'otu_table.biom', '-weight_assign', 'community_average', '-weight_files', 'ARRAY(0x3f776f0)', '-weight_identifier', 'desc') called at /usr/local/bin/copyrighter line 196
    main::copyrighter('otu_table.biom', '/media/Storage/AmpliCopyrighter/data/201210/:', 'desc', 'copyrighted_otu.biom', undef, undef) called at /usr/local/bin/copyrighter line 187

**Comment by fangly** [comment]
Dear bstamps,

Thank you for reporting this issue. I believe that you set your COPYRIGHTER_DB environment variable to "/media/Storage/AmpliCopyrighter/data/201210/:", which is not a valid file. You probably need to set it to "/media/Storage/AmpliCopyrighter/data/201210/ssu_img40_gg201210.txt" instead.

As you see above, the next release of CopyRighter will check the validity of COPYRIGHTER_DB and issue an informative error message if need be.

Best regards,

Florent

**Comment by bstamps** [comment]
That did the trick, thank you!
